version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - "type: dependencies"
      - "area: runtime"
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - "type: dependencies"
      - "area: ci"
